---
# These are the secrets to be served as files. They are base64-encoded.
# They will appear at /var/run/passwords/{secret_name} in the app container.
secretfiles:
  superSecretPassword1: czNjcmV0  # "s3cret"
  superSecretPassword2: cGE1NXdvcmQ=  # "pa55word"

# These are the secrets to be served as environmental variables. They are base64-encoded.
secretvars:
  superSecretPassword3: aGlkZGVu  # "hidden"
  superSecretPassword4: aW52aXNpYmxl  # "invisible"
