---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: awebserver
  labels:
    app: atestapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: atestapp-webserver
  template:
    # no apiVersion or kind
    metadata:
      labels:
        app: atestapp-webserver
    spec:
      containers:
        - name: awebserver
          image: "zannen/webserver:{{.Values.webserverVersion}}"
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          startupProbe:
            httpGet:
              path: /
              port: 80
            failureThreshold: 6
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 0
            failureThreshold: 3
            periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: awebserver
  labels:
    app: atestapp
spec:
  ports:
    - protocol: TCP
      targetPort: 80   # in container
      port: 8880       # across cluster on ClusterIP
      nodePort: 30880  # from outside cluster
  selector:
    app: atestapp-webserver
  type: NodePort
