---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbserver
  labels:
    app: atestapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dbserver
  template:
    # no apiVersion or kind
    metadata:
      labels:
        app: dbserver
    spec:
      containers:
        - name: mysql
          image: mysql:5.6
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: atestapp-passwords
                  key: dbPassword
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: atestapp
spec:
  ports:
    - protocol: TCP
      targetPort: 3306  # in container
      port: 3306        # across cluster on ClusterIP
      # nodePort        # from outside cluster
  selector:
    app: dbserver
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volume
  labels:
    app: atestapp
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/atestapp-asynchhashservice-mysql"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
