---
apiVersion: v1
kind: Secret
metadata:
  name: asecretserver-password-files
# Types: https://kubernetes.io/docs/concepts/configuration/secret/#secret-types
type: Opaque
data:
  # {{- range $key, $value := .Values.secretfiles}}
  {{$key}}: {{$value}}
  # {{- end}}
