---
customMetrics:
  apiService:
    # There can be only one custom metrics APIService in the cluster.
    # Set deploy=true for the first deployment, otherwise set deploy=false.
    deploy: true

    # caBundle is one or more certificates (in base64-encoded PEM format) used
    # by the custom metrics APIService.
    # If unspecified, system trust roots on the apiserver are used.
    caBundle: base64-encoded-data

  servingCert: base64-encoded-data
  servingKey: base64-encoded-data

dbPassword: base64-encoded-data

apiserverVersion: "0.0.11"
metricsexporterVersion: "0.0.3"

redisQueue: dazzle
