---
apiVersion: v1
kind: Service
metadata:
  name: awebserver
  labels:
    app: atestapp
spec:
  ports:
    - protocol: TCP
      targetPort: 80   # in container
      port: 8880       # across cluster on ClusterIP
      nodePort: 30880  # from outside cluster
  selector:
    app: atestapp-webserver
  type: NodePort
