---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: webcontent-pv-volume
  labels:
    app: atestapp
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/atestapp-cronjob-webcontent"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webcontent-pv-claim
  labels:
    app: atestapp
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
