---

name: App - Asynch Hash Service

"on":
  pull_request:
    branches:
      - develop
      - main
    paths:
      - 'asynch-hash-service/**'

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install packages
        run: |
          sudo apt update
          sudo env DEBIAN_FRONTEND=noninteractive apt install -y --no-install-recommends python3-pip python3-virtualenv

      - name: Type-check with mypy
        run: |
          tmpdir="$(mktemp -d)"
          venv="$tmpdir/venv"
          virtualenv "$venv"
          source "$venv/bin/activate"
          pip install mypy types-requests
          cd asynch-hash-service/docker/apiserver
          mypy --ignore-missing-imports .

      - name: Lint with pylint
        run: |
          tmpdir="$(mktemp -d)"
          venv="$tmpdir/venv"
          virtualenv "$venv"
          source "$venv/bin/activate"
          pip install pylint
          cd asynch-hash-service/docker/apiserver
          pip install -r requirements.txt
          pip install -r test-requirements.txt
          ../../../.pylint.sh .

      - name: Tests
        run: |
          tmpdir="$(mktemp -d)"
          venv="$tmpdir/venv"
          virtualenv "$venv"
          source "$venv/bin/activate"
          pip install pytest
          cd asynch-hash-service/docker/apiserver
          pip install -r requirements.txt
          pip install -r test-requirements.txt
          pip install -e .
          pytest

      - name: Coverage
        run: |
          tmpdir="$(mktemp -d)"
          venv="$tmpdir/venv"
          virtualenv "$venv"
          source "$venv/bin/activate"
          pip install coverage pytest
          cd asynch-hash-service/docker/apiserver
          pip install -r requirements.txt
          pip install -r test-requirements.txt
          pip install -e .
          coverage run -m pytest
          coverage report
