---

name: App - redis-queue-hpa - push to DockerHub

"on":
  pull_request:
    branches:
      - develop
      - main
    types:
      - closed
    paths:
      - 'redis-queue-hpa/docker/metricsexporter/**'

jobs:

  metricsexporter-getversion:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    outputs:
      version: ${{ steps.getv.outputs.version }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install packages
        run: |
          sudo apt update
          sudo env DEBIAN_FRONTEND=noninteractive apt install -y --no-install-recommends python3-pip python3-virtualenv

      - name: Get image version for docker tag
        id: getv
        run: |
          cd redis-queue-hpa/docker/metricsexporter
          virtualenv /tmp/venv
          source /tmp/venv/bin/activate
          pip install PyYAML==6.0.2
          python getversion.py >> "$GITHUB_OUTPUT"

  metricsexporter-docker:
    needs: metricsexporter-getversion
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:redis-queue-hpa/docker/metricsexporter"
          push: true
          tags: "${{ vars.DOCKER_USERNAME }}/metricsexporter:${{ needs.metricsexporter-getversion.outputs.version }}"
