---

name: App - redis-queue-hpa - push to DockerHub

"on":
  pull_request:
    branches:
      - develop
      - main
    # types:
    #   - closed
    paths:
      - 'redis-queue-hpa/docker/metricsexporter/**'

jobs:

  metricsexporter-docker:
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:redis-queue-hpa/docker/metricsexporter"
          push: true
          tags: "${{ vars.DOCKER_USERNAME }}/metricsexporter:latest"
