---

name: Python

"on":
  pull_request:
    branches:
      - develop
      - main
    paths:
      - '**.py'

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install packages
        run: |
          sudo apt update
          sudo env DEBIAN_FRONTEND=noninteractive apt install -y --no-install-recommends python3-pip python3-virtualenv
          virtualenv /tmp/venv
          source /tmp/venv/bin/activate
          pip install -r test-requirements.txt

      - name: Lint with flake8
        run: |
          source /tmp/venv/bin/activate
          flake8 .

      - name: Lint with black
        run: |
          source /tmp/venv/bin/activate
          black --check .

      - name: Lint with isort
        run: |
          source /tmp/venv/bin/activate
          isort --check .
