---

name: Shell

"on":
  pull_request:
    branches:
      - develop
      - main

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install packages
        run: |
          sudo apt update
          sudo env DEBIAN_FRONTEND=noninteractive apt install -y --no-install-recommends shellcheck

      - name: Lint with shellcheck
        run: |
          find -name '*.sh' | xargs shellcheck
